### ISSUE TITLE
Licensing to MIT and Apache 2.0

### ISSUE THREAD

**Issue by zyrolasting** [zyrolasting/racket-koans#29]
@shhyou @bennn 

I never put a license on this project and will do so soon. To keep consistent with Racket's source I am intending to assign MIT and Apache 2.0. While the copyright for the project as a whole has been mine as a consequence of being unlicensed, it's only right that your affirmative consent as contributors be a part of any transition where your work is yours.

If you are okay with this change, please reply with something like "I hereby relicense my contributions to `racket-koans` under the MIT license and the Apache 2.0 license."

If you deny consent or do not respond by June 1st, then I'll remove your code.

**Comment by shhyou** [comment]
I, Shu-Hung You, give permission to license my contributions to racket-koans under MIT/Apache 2.

**Comment by bennn** [comment]
I hereby relicense my contributions to racket-koans under the MIT license and the Apache 2.0 license.

**Comment by zyrolasting** [comment]
Thank you both. That's all
