### ISSUE TITLE
Definitions

### ISSUE THREAD

**Issue by soegaard** [zyrolasting/racket-koans#4]
Great project.

I noticed this comment 1.:

> ; `define`'s rules might end up a little constraining.
> (define (defined-function-defines-so-many-defines-with-define-make-it-stop)
>   (define a 0) ; 1. all defines must appear at the start of a function definiton.
>   (define b 1) ; 2. You must write a new (define) for every new binding.
>   (define c 2)
>   (define d 3)
>   (+ a b c d))

You need to define a value before it is referenced, but there is no requirement for all definitions to appear all expressions.

Example:

```
#lang racket
(define (foo)
  (define a 1)
  a
  (define b 2)
  b)

(foo)

```

**Comment by zyrolasting** [comment]
Great, thanks for that! I'll adjust the language.

**Comment by zyrolasting** [comment]
#5
